### ISSUE TITLE
bug in splice()

### ISSUE THREAD

**Issue by vrz** [cesanta/v7#479]
node -e "s=[]; s.splice(0,0,'aaa'); console.log(s);"
[ 'aaa' ]

v7 -e "s=[]; s.splice(0,0,'aaa'); print(s);"
[]
null

**Comment by jack126guy** [comment]
I think this is due to `a_splice` line 14334 (14335 if you count the Unicode line separator on line 2900):

    if (len <= 0) return res;

This bounds check was originally in `Array_slice` so any slice of an empty array will return an empty array. But now that both `Array_slice` and `Array_splice` rely on `a_splice`, this bounds check is erroneous.

Changing the line to:

    if (!mutate && len <= 0) return res;

Seems to fix it.

**Comment by cpq** [comment]
@jack126guy , thank you.
Fixed.
