### ISSUE TITLE
Consider defining v7_t for struct v7*

### ISSUE THREAD

**Issue by swisspol** [cesanta/v7#531]
It's kind of an anachronism to have to type `struct v7*` everywhere instead of a clean `v7_t` in 2015 :wink:

**Comment by mmikulicic** [comment]
We considered it but we opted to follow the BSD style:

https://www.freebsd.org/cgi/man.cgi?query=style&sektion=9

```
     Avoid using typedefs for structure	types.	Typedefs are problematic
     because they do not properly hide their underlying	type; for example you
     need to know if the typedef is the	structure itself or a pointer to the
     structure.	 In addition they must be declared exactly once, whereas an
     incomplete	structure type can be mentioned	as many	times as necessary.
     Typedefs are difficult to use in stand-alone header files:	the header
     that defines the typedef must be included before the header that uses it,
     or	by the header that uses	it (which causes namespace pollution), or
     there must	be a back-door mechanism for obtaining the typedef.
```

**Comment by swisspol** [comment]
I don't know... This seems like 20 years old guidelines and the state of compilers and API design patterns have evolved significantly since then :smile: 

Furthermore it seems they argue against `typedef struct {} Foo` in headers, and are not talking about opaque private structures declared in public headers like `typedef struct v7* v7_t`.

AFAIK the vast majority of C APIs have been using typedefs for opaque structures for a long time now: anything from POSIX `typedef struct _opaque_pthread_mutex_t __darwin_pthread_mutex_t` to pretty much the enter iOS / OS X stack and many system level APIs like libdispatch. Same on Linux (see GTK) and Windows.

> Typedefs are problematic because they do not properly hide their underlying type;

`typedef struct v7* v7_t;` in a public header certainly hides the underlying structure.

> for example you need to know if the typedef is the structure itself or a pointer to the structure.

You don't need to know this when designing modern C APIs. It's just an opaque type returned by a constructor function, then passed to various APIs as-is and finally passed to a destructor function. It's irrelevant to the API clients if it's a scalar, a pointer, a pointer to a pointer or whatever.

> In addition they must be declared exactly once, whereas an incomplete structure type can be mentioned as many times as necessary.

You can also declare `typedef struct v7* v7_t;` 10 times in 10 different headers in you want, this is totally supported by the C standard. Although typically you only put it in one header.

> Typedefs are difficult to use in stand-alone header files: the header that defines the typedef must be included before the header that uses it, or by the header that uses it (which causes namespace pollution), or there must be a back-door mechanism for obtaining the typedef.

So yeah, you can have `void Foo(struct temp* bar);` in a header without having to declare `struct temp` at all before... If you have `void Foo(temp_t bar);`, you must declare `temp_t` before. I fail to see how that's a problem in real-life though :wink: 

Anyway, it's not a big deal either way, but v7 API certainly stands out among the vast majority of modern C APIs (and by modern I mean maybe anything in the past 10 years).

**Comment by mmikulicic** [comment]
> You can also declare typedef struct v7* v7_t; 10 times in 10 different headers in you want, this is totally supported by the C standard. 

Yeah, it's supported since the C11 standard.

```sh
mkm@santa $ gcc -std=c99 /tmp/test.c -o /tmp/tt                                                                                                                    
/tmp/test.c:2:20: warning: redefinition of typedef 'v7_t' is a C11 feature [-Wtypedef-redefinition]
typedef struct v7 *v7_t;
                   ^
/tmp/test.c:1:20: note: previous definition is here
typedef struct v7 *v7_t;
```

Unfortunately there are still many people having embedded toolchains that just recently got upgraded to support C99.

Currently we want to aim at the widest possible portability and hence we even make our lives harder than we should be ensuring v7 and mongoose are ANSI C compatible. We might relax it to C99 soon though since that's just insane in 2015.

However, this is not an issue here. Our build artefact is a source/header pair where we fully control the order of declarations and this issue doesn't make it any harder for us to work.

It's just that we picked a set of rules we could relate with (among others) and stuck with them for consistency throughout all of our code base. Some of those rules might not make sense anymore, or they might make sense as internal rules and not on public API with opaque pointers.

> Anyway, it's not a big deal either way, but v7 API certainly stands out among the vast majority of modern C APIs (and by modern I mean maybe anything in the past 10 years).

Hmm, perhaps we're just too much old-school. Thanks for reporting, we'll definitely reconsider this.

**Comment by swisspol** [comment]
Again, no big deal, more of an oddity - that won't change my appreciation of great v7 is :smile:

**Comment by mmikulicic** [comment]
Well, don't worry we do have this kind of discussions popping up internally on a regular basis anyway; so it's good to have some external feedback as well :-)

I just wanted to mention that we aim at keeping compatibility with some old compilers. How old exactly is still an open question.

**Comment by swisspol** [comment]
I'm curious about: how is it a problem in practice? I mean people have been using `typedef struct Foo* foo_t` pre-C99 and even C89? The typedef is in a single header which has inclusion guards and is then included whatever other header needs it.

**Comment by mmikulicic** [comment]
> The typedef is in a single header which has inclusion guards and is then included whatever other header needs it.

Yeah that's exactly the problem. Programming is more often not the art of making code but changing code. When you need to just factor out a piece of code in a separate file, and you suddenly find yourself creating 5 new headers to break some dependency cycles, it starts to makes sense why a project like FreeBSD has a guideline like that.

That said, as I mentioned, a project with only one public header shouldn't need to worry about it; but since you asked I'm happy to play devil's advocate (pun intended).

**Comment by swisspol** [comment]
FWIW I spent a few years at Apple working on the OS stack, which is a ton of C / ObjC, and AFAIK this has never been a problem. You typically have a base header which has all your typedefs and is included everywhere. So it can be done.

But since your code base is private, and maybe it's used on some esoteric embedded system with limited C compilers, I might be missing something :wink:
