### ISSUE TITLE
Allow sizep to be NULL in v7_to_string()

### ISSUE THREAD

**Issue by swisspol** [cesanta/v7#532]
The returned string is NUL terminated anyway, so the client doesn't always need the length. It's also kind of an implicit convention of C APIs that take a length pointer to allow it to be NULL when it makes sense.

**Comment by mmikulicic** [comment]
hmm, turns out that the current API for accessing string data was fundamentally wrong; your request brought this to our attention and we decided to fix it at the root:

The documentation was misleading. It's true that all the owned strings were guaranteed to be NUL terminated, but that hides two key problems:

1. not all strings are "owned" strings
2. not all JS strings, even owned ones, are necessarily valid C strings even if they are NUL terminated. This is because they might contain embedded NUL chars

We added the NUL terminator to all owned strings in order to simplify the interaction with C APIs, but if C code cannot determine whether a string was created as 

Thus in 2254e005043ef2cbd077358044ad820bc78073e3 we changed the string API as:

- `v7_get_string_data` returns string pointer and length. Length pointer is mandatory to avoid accidentally relying on the fact that most strings don't contain embedded NUL chars and are NUL terminated.
- `v7_to_cstring` returns a string pointer after having checked that it's indeed compatible with the expectations that a C API has about strings: It has to contain only one NUL char, and it has to be in terminal position.

**Comment by swisspol** [comment]
Glad to be of help!

> All strings owned by the V7 engine (see v7_create_string) are guaranteed to be NUL terminated.

That's not very clear IMO. The doc for `v7_create_string()` doesn't explained what's an owned string and what is not. I assume owned means you passed non-zero to the `copy` arg when creating the string?

Side question: does that mean one can (should?) use v7 strings to store arbitrary data blobs or is there another recommended construct?

**Comment by mmikulicic** [comment]
yeah, v7_create_string documentation sucks, iirc there is another issue that already mentions that, I'll report there when fixed.

But yeah you assumed right. An owned string is copied in JS managed heap and will get reclaimed by the GC. We need to fix doc and make sure the nomenclature is not confusing.

v7 strings are currently the most memory efficient way to store read only byte arrays. We use them extensively in the embedded APIs of Smart.js to hold binary data. Also see https://www.cesanta.com/developer/v7#_non_standard_api

Ideally we should use standard typed arrays / array buffers / dataviews. We'll likely do that, but don't hold your breath, probably not this year :-)

**Comment by swisspol** [comment]
This issue I assume #524.

**Comment by mmikulicic** [comment]
correct

**Comment by swisspol** [comment]
Now that #536 is partially fixed, I'm looking at the updated code:
```
const char *v7_to_cstring(struct v7 *v7, v7_val_t *value) {
  size_t size;
  const char *s = v7_get_string_data(v7, value, &size);
  if (s[size] != 0 || strlen(s) != size) {
    return NULL;
  }
  return s;
}
```

I don't really understand this code: if the string is *not* owned by v7, then isn't `s[size]` a buffer overflow?

FWIW I'm also a bit skeptical about the usefulness of this new `v7_to_cstring()`. In practice, text strings very very rarely contain NUL chars. I bet the most client will plainly ignore the potential NULL result. So then what's the point?

How about this API instead:
- `v7_get_string_data()`:
 - Works for owned and non-owned strings
 - Always returns non-NULL
 - It's OK to pass a NULL length pointer (it's the client's problem, maybe they use the string as a byte array and don't care about the length as they already know it)
 - The client cannot assume there is an extra NUL byte after the end of the buffer
- `v7_to_cstring()`
 - Only works for owned strings
 - Always returns non-NULL for owned strings or NULL otherwise
 - Always NUL terminated
 - Using it on a string that contains NUL characters is undefined (if your strings have NUL characters, fall back to `v7_get_string_data()`)

It's more strict and easier to understand IMO.

**Comment by swisspol** [comment]
Trying to make point more clear: I just don't see how `v7_to_cstring()` is supposed to help by returning NULL? Saving the client from a truncated C string? I bet a lot of clients won't check for NULL and crash. Is this really better than a truncated string?

If yes, what about UTF8 then? Aren't v7 strings supposed to be valid UTF8? I would then expect `v7_to_cstring()` to return valid UTF8 bytes. Why is this API not validating the string for UTF8 encoding as well and returning NULL if invalid?

At some point, it's fair game to draw the line and give the API user enough rope to hang themselves with if they want to :wink:

**Comment by mmikulicic** [comment]
> Besides, it's doing an extra strlen(), which can be costly and redundant.

This is an implementation detail, we might just move the classification at string creation time and have a constant time check when returning the string.

> I don't really understand this code: if the string is not owned by v7, then isn't s[size] a buffer overflow?

Yeah it's wrong, it's just a hack to draft the API. The right way would be to check the internal string type.
Will be fixed before the next release.

> Trying to make point more clear: I just don't see how v7_to_cstring() is supposed to help by returning NULL? Saving the client from a truncated C string? I bet a lot of clients won't check for NULL and crash. Is this really better than a truncated string?

I believe a crash is better than a subtle misbehaviour.

There are different kinds of ropes. There is one that elicits "a-ha", ones that trigger "m-key", and others that are just make you go "!@#%!".

> It's OK to pass a NULL length pointer (it's the client's problem, maybe they use the string as a byte array and don't care about the length as they already know it)

Yeah making the length optional is ok. I think the naming `v7_get_string_data

> If yes, what about UTF8 then? Aren't v7 strings supposed to be valid UTF8? I would then expect v7_to_cstring() to return valid UTF8 bytes. Why is this API not validating the string for UTF8 encoding as well and returning NULL if invalid?

Makes sense, not urgent since it doesn't require the API to be changed. As mentioned previously, asserting the type of the string can and possibly should be done at string creation time, and not check at avery access.

**Comment by mmikulicic** [comment]
clarification: your suggestion of making `v7_to_cstrings` work only for unowned strings looks tempting but it has two problems:

1. it would drop the possibility of storing C compatible strings on flash memory.
2. it mixes up the concepts of string content and string backing store.

Data for owned strings live on the JS heap and are managed by a compacting GC collector, which actually moves data around. We cannot have an owned string whose content lives on read only memory.

----

The idea behind this new API is simple:

If you expect your strings to be C strings because you will pass it down to other functions expecting a C string you should call `v7_to_cstring`. In that case you don't need the length so you'll naturally pick that function also because it offers the signature that most suits your needs.

If you operate on strings as byte arrays or JS strings (basically sequences of `\0` terminated utf8 chunks)
you need to use the more low level `v7_get_string_data`.

Whether a string is owned or unowned is orthogonal to this. I expect most users to just use `v7_to_cstring`.

This very thread highlights how for a casual access to strings you don't want to care about string length nor about the corner cases when a JS string contains embedded NUL chars. This is a quite special corner-case and so most users won't care; they will use `v7_to_cstring`.

Only when you write more low level code that needs to access the underlying raw bytes `v7_get_string_data` is useful to you.

Now we just have to make a sound implementation and remove that ugly hack.
