### ISSUE TITLE
V7 Windows 7 32 bit

### ISSUE THREAD

**Issue by ScriptBasic** [cesanta/v7#569]
I compiled my V7 extension module for Script BASIC under Windows 7 32 bit OS using TDM-GCC32 and I can't seem to return a pointer to a requested JavaScript variable even thought the return code says success. 

Is there any docs on compiling for Windows?

**Comment by ScriptBasic** [comment]
I was able to compile V7.EXE and it seems to work. I can't figure out why my Script BASIC extension module isn't returning pointers to JavaScript variables. Works great under Linux 64 bit.

**Comment by ScriptBasic** [comment]
```
#ifdef V7_WINDOWS
typedef unsigned __int64 uint64_t;
```
How does this effect running on 32 bit Windows?

**Comment by mmikulicic** [comment]
it has no effect. 32 bit windows has 32 bit pointers. The C compiler can still generate code that operates on 64 bit quantities. The typedef you mention above is just needed because the microsoft C compiler doesn't use standard names such as `int64_t` but instead uses `__int64`.

Can you try on linux 32 bit (e.g. by passing the `-m32` flag to the compile) ?

**Comment by ScriptBasic** [comment]
I'm using TDM-GCC32 not MS VC. Strange only variable values seem not to be working when getting pointers to objects work.
I'm going to try it with the 64 bit version of Windows Script BASIC and use TDM-GCC64.

**Comment by ScriptBasic** [comment]
No luck compiling this as a 64 bit Windows target. It does the same thing as the 32 bit attempt.
I'm at a loss.

**Comment by ScriptBasic** [comment]
Your example worked on Windows 7 32 bit OS (in a VirtualBox) so it looks like I need to look closer at my extension module code.
```
C:\scriptbasic\source\extensions\js>gcc nextprop.c v7.c -o nextprop -lm
v7.c:149:0: warning: "fileno" redefined
 #define fileno _fileno
 ^
In file included from v7.h:207:0,
                 from v7.c:1:
C:/TDM-GCC-32/include/stdio.h:530:0: note: this is the location of the previous definition
 #define fileno(__F) ((__F)->_file)
 ^

C:\scriptbasic\source\extensions\js>nextprop
obj stringifies as: {"foo":42}
iterating properties with v7_next_prop:
prop name: "bar", attrs: 2
prop name: "foo", attrs: 0

C:\scriptbasic\source\extensions\js>
```

**Comment by ScriptBasic** [comment]
I thought my gcc build of Script BASIC for Windows 32 would solve the weird issues I'm seeing with the JS (JavaScript) extension module.

The problem seems to be how SB is handling V7 variables. It seems to be executing the functions correctly but looses it with variable retrieval. In some cases giving a Windows exception error.

Script BASIC is expecting a 32 bit long as a return type under Windows 32 bit. Everything works fine with Ubuntu 64 bit.

**Comment by ScriptBasic** [comment]
Should I assume V7 can't be used as a DLL under Windows? 
Has V7 ever been tested in this environment?

**Comment by mmikulicic** [comment]
I see no reason why V7 couldn't be used as a DLL on windows. There might be
bugs on 32-bit windows platforms but I don't see how they can be caused by
V7 being used as a DLL. Can you reproduce an issue that happens only if you
dynamically link V7 ?

**Comment by ScriptBasic** [comment]
Can you make the example I posted above work compiling V7 as a DLL on Windows 32. I really don't think it's my Script BASIC interface that's the problem. I have embedded 4 so different languages in much the same way without issue.

**Comment by mmikulicic** [comment]
could you please first confirm that the problem you're experiencing goes
away as soon as you link V7 statically instead of as a DLL ?

**Comment by ScriptBasic** [comment]
See the post above of compiling V7 as an .exe under Windows 32.

**Comment by mmikulicic** [comment]
> It seems to be executing the functions correctly but looses it with variable retrieval. 

what do you mean by "looses it" ?

> In some cases giving a Windows exception error.

which exception ? can you get a stack trace? 
You should be able to get a stack trace with your C debugger (gdb?)

> Is there any chance this might a std call / cdec issue?

V7 is written purely in C and thus if you compile the library and the call sites with the same headers and the same C compiler the calling convention doesn't matter

I'm a little bit suspicious about this code:

```
rcode = JS::EXEC(jsobj, jscode)
```

can you show me how you call `v7_exec` ?

**Comment by ScriptBasic** [comment]
"can you show me how you call v7_exec ?"

```
besFUNCTION(js_exec)
  VARIABLE Argument;
  LEFTVALUE Lval;
  unsigned long __refcount_;
  DIM AS unsigned long v7;
  DIM AS const char *js_code;
  DIM AS v7_val_t result;
  enum v7_err rcode = V7_OK;
  besARGUMENTS("iz")
    AT v7, AT js_code
  besARGEND
  rcode = v7_exec(v7, js_code, &result);
  Argument = besARGUMENT(3);
  besLEFTVALUE(Argument,Lval);
  besRELEASE(*Lval);
  *Lval = besNEWLONG;
  LONGVALUE(*Lval) = rcode;
  besRETURN_LONG(result);
besEND
```

**Comment by mmikulicic** [comment]
> Keep in mind that V7 works fine under Ubuntu 16.04 64 bit.
you mean V7 invoked by the same ScriptBasic code in a ScriptBasic interpreter built from the same sources ?

**Comment by ScriptBasic** [comment]
The JS C extension module code is the same for Linux as it is for Windows.

**Comment by mmikulicic** [comment]
I'm a little bit confused by your argument naming:

```
jsobj = JS::CREATE()
rcode = JS::EXEC(jsobj, jscode)
PRINT rcode,"\n"
JS::DESTROY(jsobj)
```

From here it seems that `rcode` is the return code of `v7_exec` (a code that tells whether it's success or failure).

But in the bindings guts it's clear that you actually return another thing, the `result` (a `v7_val_t` value):

```
  rcode = v7_exec(v7, js_code, &result);
...
  besRETURN_LONG(result);
```

I have no idea how the internals of the ScriptBasic <-> C bindings work (and you'll have to forgive me but I don't really have the time to invest in learning them), but just an educated guess:

is it possible that `  besRETURN_LONG(result);` assumes that `result` is a `long` ?

`v7_val_t` is a `uint64_t` value that encodes a javascript value (either inline or as a reference to a structure held on the heap); you can read more about this implementation detail in https://docs.cesanta.com/v7/master/#/v7-internals/nan-packing.md/.

**Comment by ScriptBasic** [comment]
"is it possible that besRETURN_LONG(result); assumes that result is a long ?"
Yes,

My gut feeling is V7 is returning pointers to v7_val_t type variable that don't conform to a 32 bit LONG.

**Comment by mmikulicic** [comment]
1. V7 is not returning pointers to a `v7_val_t` variable. You are passing a pointer to a `v7_val_t` variable to V7:

```c
rcode = v7_exec(v7, js_code, &result);
```

2. `v7_val_t` is a 64-bit value, on any platform; it's defined as `typedef uint64_t v7_val_t`.

3. why are you returning `result` as a 32 bit LONG in the first place ?

Keep in mind that the signature of v7_exec is:

```
enum v7_err v7_exec(struct v7 *v7, const char *js_code, v7_val_t *result);
```

all you care about the return code of v7_exec is whether it is `V7_OK` or not.
The real result of evaluating the expression is stored in `result`.

If you don't need the `result` (e.g. you're just interested, you can pass NULL:

```c
enum v7_err rcode = v7_exec(v7, "print('hello')", NULL);
if (rcode != V7_OK) {
  printf("cannot evaluate JS code\n");
}
```

If you need the result, you pass the address of a 64-bit variable (always 64-bit!). This variable will store a JS value, but content of the C variable is opaque to you: you can access it only via accessor functions, e.g.:

```c
v7_val_t res;
enum v7_err rcode = v7_exec(v7, "1 + 2", res);
if (rcode != V7_OK) {
  printf("cannot evaluate JS code\n");
  exit(1);
}
printf("result: %d\n", (int)v7_get_double(v7, res));
```

Thus, your example `PRINT rcode,"\n"` is suspicious in two ways:

a. you called the variable `rcode` while your BASIC<->V7 glue code clearly returns a `result`

b. you attempt to print a `v7_val_t` as if it were something you can just print as a LONG or any other primitive value. If you want to print `v7_val_t` values, we provide the `v7_print*` helpers.

**Comment by ScriptBasic** [comment]
Bottom line is my code works fine on Ubuntu 64 bit. 

V7 isn't returning valid data for any request variable value not just results of a v7_exec().

**Comment by mmikulicic** [comment]
as I said, the issue you're having is likely caused by the fact you're assuming `v7_val_t` must be a 32-bit LONG, which it clearly isn't.

It might work on Ubuntu 64 bit just beacuse on that arch, `sizeof(long) == 8` and the calling convention there is friendlier in case of incorrect parameters pushed on stack (since in cdecl the cleanup happens at the caller side).

We support V7 only so far its API is invoked from C code. The API contract is clearly specified in our header file; please make sure your glue is correctly respecting all the declared parameter and respective sizes.

This is usually the job of the C compiler to detect any incorrect usage. Once you start to perform C calls via glue code that doesn't look like C at all to me, I'm really sorry but I cannot help you, unless you narrow it down to an issue that can be shown with a (short) C code snippet.

**Comment by ScriptBasic** [comment]
I'm using TDM-GCC32 under Windows. The C preprocessor 'mask' to make C look more like BASIC is not 'clue but standard varidec calling method. I don't understand how V7 fakes a 64 value under 32 bit Windows. 

Did you ever try my DLL example printing "Hello Script BASIC"?

**Comment by mmikulicic** [comment]
> I don't understand how V7 fakes a 64 value under 32 bit Windows.

it doesn't need to fake it. `uint64_t` is full supported under 32 bit windows.
A 32 bit architecture uses 32-bit for pointers, while a 64-bit architecture uses 64-bit as pointers.
The native words size (and thus the register size) of CPUs implementing these architectures it's usually the same as the pointer size, but there have been notable exceptions such as the motorola 68000 (atari, amiga, early macs): 16-bit architecture; registers and pointers are all 32-bit.

But that's all about hardware. The C compiler can deal with values that are bigger than a hardware word, e.g. structures. You can pass a structure of 10 32-bit integers by value, and the compiler will just issue the necessary instructions to copy the data piece wise. 

Handling `uint64_t` (aka. `long long int`) variables on 32-bit architectures is usually implemented by splitting it into two registers (e.g. `%edx:%eax` on some calling conventions).

Read more at: http://www.unix.org/version2/whatsnew/lp64_wp.html


> Did you ever try my DLL example printing "Hello Script BASIC"?
no I didn't try it sorry; if you want to get the most out of this open source support channel, you should isolate the problem and make a small and self contained bug report that is easily reproduced by other people. You shouldn't expect people to download and build Script BASIC just to reproduce an issue with a library that you're using.

speaking of which:

>  The C preprocessor 'mask' to make C look more like BASIC is not 'clue but standard varidec calling method.

What matters to this bug report is the exact C code that is generated by this preprocessor "mask". Please just paste the macro expansion of:

```
besFUNCTION(js_exec)
  VARIABLE Argument;
  LEFTVALUE Lval;
  unsigned long __refcount_;
  DIM AS unsigned long v7;
  DIM AS const char *js_code;
  DIM AS v7_val_t result;
  enum v7_err rcode = V7_OK;
  besARGUMENTS("iz")
    AT v7, AT js_code
  besARGEND
  rcode = v7_exec(v7, js_code, &result);
  Argument = besARGUMENT(3);
  besLEFTVALUE(Argument,Lval);
  besRELEASE(*Lval);
  *Lval = besNEWLONG;
  LONGVALUE(*Lval) = rcode;
  besRETURN_LONG(result);
besEND
```

**Comment by ScriptBasic** [comment]
Here is the JS::EXEC() C function expanded.
```
# 715 "interface.c"
__attribute__((dllexport)) int js_exec(pSupportTable pSt, void **ppModuleInternal, pFixSizeMemoryObject pParameters, pFixSizeMemoryObject *pReturnValue){ pExecuteObject pEo=
# 715 "interface.c" 3 4
((void *)0)
# 715 "interface.c"
;
  VARIABLE Argument;
  LEFTVALUE Lval;
  unsigned long __refcount_;
  unsigned long v7;
  const char *js_code;
  v7_val_t result;
  enum v7_err rcode = V7_OK;
  int iError; iError = pSt->basext_GetArgsF(pSt,pParameters,("iz"),
    & v7, & js_code
  ); if( iError )return iError;
  rcode = v7_exec(v7, js_code, &result);
  Argument = ((3) <= (pParameters ? pParameters->ArrayHighLimit : 0) ? pParameters->Value.aValue[(3)-1]: 
# 727 "interface.c" 3 4
            ((void *)0)
# 727 "interface.c"
            );
  do{if( (((Argument))->vType) == 4 ){ __refcount_ = pSt->pEo->pMo->maxderef; Lval=(Argument)->Value.aValue; while( *(Lval) && ((*(Lval))->vType)== 4 ){ (Lval=(*(Lval))->Value.aValue); if( ! __refcount_ -- ){ return 12; } } }else Lval=
# 728 "interface.c" 3 4
 ((void *)0)
# 728 "interface.c"
 ;}while(0);
  (pSt->ReleaseVariable(pSt->pEo->pMo,(*Lval)));
  *Lval = (pSt->NewLong(pSt->pEo->pMo));
  ((*Lval)->Value.lValue) = rcode;
  do{(*pReturnValue) = (pSt->NewMortalLong(pSt->pEo->pMo,pSt->pEo->pGlobalMortalList)); if( (*pReturnValue) == 
# 732 "interface.c" 3 4
 ((void *)0) 
# 732 "interface.c"
 )return 1; (((*pReturnValue))->Value.lValue) = (result); return 0; }while(0);;
return 0;}
```

**Comment by mmikulicic** [comment]
Ok, so calling conventions are unlikely to have anything to do, the basic<->C bridge code doesn't go anywhere that low level:

The return value of the basic function is returned through the `pFixSizeMemoryObject *pReturnValue` argument.

```
(((*pReturnValue))->Value.lValue) = (result);
```

(I assume `lValue` is defined as `long`.)

Your C compiler should have warned you of downcasting an `uint64_t` to a `long`, but unfortunately `gcc` doesn't warn about that by default: you should add the `-Wconversion` to your gcc invocation.

In any case, that shouldn't cause a crash since all you're doing is printing a long with `PRINT`; in any case you'd get a number that is meaningless

please include a stack trace (e.g. obtained by gdb) of your crash, just in case we can see something obvious there.

**Comment by ScriptBasic** [comment]
"you should add the -Wconversion to your gcc invocation."

Can you show me an example?

**Comment by mmikulicic** [comment]
```gcc -Wconversion -o foo foo.c```

**Comment by ScriptBasic** [comment]
Maybe #include <stdint > might solve the problem.

**Comment by mmikulicic** [comment]
I don't see how including stdint could help. And btw, stdint is included by `v7.h`

To summarize:

1. your code is incorrect; you're mixing up rcode and result and assuming result is a 32-bit value that makes sense printing.

2. it doesn't seem that this instance of incorrect usage can be the cause of the crash you mentioned; but that's hard to say since you didn't include a stack trace.

3. you mentioned that also other "variable accesses" fail in a similar way. Please provide more context in a way that is self-contained in a comment or provide clear references to other comments that you wrote in other issues, if any.

It's still possible that there is a V7 bug hidden somewhere; but I really cannot do anything about it unless you provide more information about the crash.

**Comment by ScriptBasic** [comment]
You could save us both a lot of time if you would create a simple DLL example to prove to yourself that it's not Script BASIC's issue and a bug in V7 running under Windows 32 bit.

**Comment by mmikulicic** [comment]
sorry, I don't have a windows machine at hand otherwise I might have just did that; we do however run automated v7 unit tests on windows 2012 server and I routinely try out v7.exe built with VisualC 6.0 on wine (windows emulator on linux), so I'm pretty confident that the basics just work.

the thing that would be of great help is a stack trace of the crash. Please run your app under `gdb` and when it crashes just type `bt` and paste here the result.

**Comment by ScriptBasic** [comment]
I don't believe there is a 'gdb' for Windows. 

Maybe someone from Cesanta will read this thread and have a Windows machine to test their software on. I have already spent too much time trying to convince the V7 project they have a DLL bug under Windows.

**Comment by ScriptBasic** [comment]
I tried your suggestion of using gdb to produce the debug info you needed but Script BASIC is an interpreter and I would have to recompile it with the -ggdb option for it to detect debug symbols. Just compiling the js.dll with -ggdb wasn't enough.

```
C:\sbgcc\examples\js>gdb scriba js_hello.sb
GNU gdb (GDB) 7.8.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "i686-w64-mingw32".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from scriba...(no debugging symbols found)...done.
"C:\sbgcc\examples\js/js_hello.sb" is not a core dump: File format not recognized
(gdb)
```
Please reopen this thread until it is resolved.

**Comment by mmikulicic** [comment]
> Why would you CLOSE this thread when the issue is still unresolved?

the reasons I closed the issue are:

1. the problem you described is vague: "a Windows exception error" (which one? more details please). There is nothing we can do until you make a proper bug report. **Action item** on you: provide us with a stacktrace of the crash you're experiencing. You can do that with any debugger. `gdb` was my pick, but if you're not familiar with it, please just use any debugger. If you are not familiar with any, I suggest you invest some time learning how to use them; they are a fantastic tool.

2. the bug report doesn't clearly isolate an issue with V7. You are wrapping V7 into another programming language, which has its own DSL that implements foreign function calls to C. **Action item** on you: provide a smaller, self contained (no BASIC involved) example where you show that V7 is misbehaving (either because of a bug or because our documentation doesn't clearly show how to do something correctly).

3. you ask me to build a DLL on windows to reproduce the issue. **Action item** on you: Please send me the code of a simple DLL and main program that uses the DLL; I might be able to find the issue just by reading the sources, or if not, I'd be intrigued and I'd find the time to compile it and run it on some windows machine. 

4. we reached some results: identified that you incorrectly assume a `v7_val_t` is castable to a  `long`. **Action item** on you before progressing is thus: fix your Bas<->V7 stubs so they don't cast v7 values to long and correctly access the `v7_val_t` values (e.g. with `v7_get_double`, `v7_println`, etc).

We're happy to help you learn how to use V7 and improve our documentation if we got something wrong.

But we cannot help you dealing with integration of V7 with ScriptBasic, or to run a debugger. I see why you're fascinated with programming languages and interpreters, it's a topic I always loved since I started programming; I'd be glad if I could help you nurture this interest, there are so many things to learn. But this is not right place nor we don't have time for this kind of support.

----

In other words:

This is an issue tracker for V7. V7 is a JavaScript virtual machine exposed as a library so 
that it can be embedded in other programs. V7 has a well defined interface towards the
program that embeds it. Any violation of the expected behaviour of a library implementing
that interface is considered by us a bug, which includes crashes caused by correct usage
of the library. Any shortcomings in the API design can also be discussed since its not perfect;
but they would not be considered as implementation bugs.

In order to help fixing the issues of the Open Source product, reporters are kindly requested
to do their due diligence, which among other things include trying to find the smallest example
that reproduces the issue and make it easy to other people to actually reproduce the issue

In case of libraries like V7, it usually means attaching the full source code that shows the
problem and detailed instructions about how to build it, possibly not requiring cumbersome,
dependencies.

I'm not making up these concepts, e.g. read http://contribution-guide-org.readthedocs.io/ or other similar bug report / contributor's guidelines.

---

I'd happily reopen the issue once you address these issues in the bug report, since that will mean that we'll be better equipped to solve the issue once better identified.

Seriously, please just address some of the action items I highlighted for you before commenting further; I'd really want to help; but I need some cooperation. We're offering this product and this support for free; you'll agree with us that there have to be boundaries in the depth of interaction we have with each user. Focused, direct bug reports will thus have the best chance of be addressed.

**Comment by ScriptBasic** [comment]
If I can get this to work on Windows, I might have a commercial license deal for you guys,

**Comment by mmikulicic** [comment]
> If I can get this to work on Windows, I might have a commercial license deal for you guys,

For commercial support please contact us at https://www.cesanta.com/contact

**Comment by mmikulicic** [comment]
@ScriptBasic: I added a windows DLL example in the `examples/dll` (added in commit 7562a01e582a0661a805d1f2ebd8033af42d8199 ), just to show that it works fine on windows and DLL is a supported platform.

**Comment by ScriptBasic** [comment]
Cloud you post you C example calling V7 in a Windows environment? Thanks for taking the time to test this!

**Comment by ScriptBasic** [comment]
Can you post in the example directory the C program calling the DLL under Windows/Wine?

**Comment by mmikulicic** [comment]
as you see from the Makefile in https://github.com/cesanta/v7/blob/master/examples/dll/Makefile

 the C files are living in another directory:

https://github.com/cesanta/v7/blob/master/examples/call_js_from_c/main.c

this calls the exported `v7_example` function from a DLL built with the https://github.com/cesanta/v7/blob/master/examples/call_js_from_c/call_js_from_c.c and https://github.com/cesanta/v7/blob/master/v7.c files

**Comment by ScriptBasic** [comment]
There was never a dispute V7 couldn't be compiled to Windows DLL, Making it work is the problem. Please show me your version of the example I have in Script BASIC.

**Comment by ScriptBasic** [comment]
I'll play around with casting the returned v7_val_t values and see if it helps.

**Comment by ScriptBasic** [comment]
I can't figure out why V7 is crashing and I've spent way too much time trying to resolve it. Cesanta doesn't seem to have much interest in Windows anyways, I'll continue my V7 efforts under Ubuntu 64 bit and revisit this if I have time.

Thanks for your help!

**Comment by mmikulicic** [comment]
> I'll continue my V7 efforts under Ubuntu 64 bit and revisit this if I have time

If it crashes on windows 32-bit and works under Ubuntu 64-bit, it's not because windows or ubuntu, but because 32-bit vs 64-bit. 

You're likely using it wrong (as discussed) and you might just got lucky on 64-bit platforms.

> Cesanta doesn't seem to have much interest in Windows anyways

I don't see how you reached that conclusion; Our examples can be built and **run** on windows
In particular https://github.com/cesanta/v7/blob/master/examples/call_js_from_c/call_js_from_c.c, 
invokes the API you complained that doesn't work for you and much more.

I even went to great length to check that it works as a DLL, since you raised a concern that (I quote) "Should I assume V7 can't be used as a DLL under Windows?".

I tested that on Windows and it works just fine.

---

What is central to understand here is that are happy to engage with genuine and constructive bug reports, which this was not.

What you basically done in this issue is: "Here's a Basic interpreter I'm working on; it can call C code through complicated macro-based FFI mechanism; I used it to invoke V7 and it crashed on windows; please help me by downloading and compiling ScriptBasic on your windows machine, loading my custom code and figuring out why it crashes, since it must be a bug in V7 support for windows".

I did all I could to help you, short of actually looking at the internals of ScriptBasic and running it. 
I pointed at what was my best guess at the source of the issue (treating `v7_val_t` as a `long`, which is incorrect and indeed breaks 32-bit archs) and asked for stack traces which you didn't provide.

You just cannot expect me to build and run ScriptBasic. That is the thing we don't have any interest in. Not Windows.

The stack traces are an important diagnostic tool that might have helped us figuring out what you did wrong. If you don't know how to capture them, I sincerely suggest you improve your software development skills before endeavouring into things that might be over your head. 

---

Given all the above, it's preposterous to imply that Cesanta doesn't have much interesting in Windows.

I'm going to lock this conversation and I do it again on future issue reports that don't meet basic quality criteria.
